---
# Copyright 2016 IBM Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Create glance database
  mysql_db: name=glance
            state=present

- name: Create glance database user
  mysql_user: name=glance
              password={{ GLANCE_DBPASS }}
              priv=glance.*:ALL
              host={{ item }}
              state=present
              append_privs=yes
  with_flattened:
    - "{{ DB_HOST }}"

- name: Copy glance.sh to create user and entity
  template: src=glance.sh
            dest={{ BASE_DIR }}/glance.sh
            owner=root
            group=root
            mode=0644

- name: Run glance.sh
  shell: bash {{ BASE_DIR }}/glance.sh

- name: Install glance packages
  apt: name={{ item }}
       state=present
  with_items:
    - "{{ glance_packages }}"

- name: Copy config file for glance
  template: src={{ item }}
            dest=/etc/glance/{{ item }}
            owner=root
            group=root
            mode=0644
  with_items:
    - glance-api.conf
    - glance-registry.conf

- name: Restart glance service
  service: name={{ item }}
           state=restarted
  with_items:
    - glance-registry
    - glance-api

- name: Sync glance database
  shell: su -s /bin/sh -c "glance-manage db_sync" glance
  # ignore_errors: True

- name: Copy glance-cirros.sh
  template: src=glance-cirros.sh
            dest={{ BASE_DIR }}/glance-cirros.sh
            owner=root
            group=root
            mode=0644

- name: Verification for glance
  shell: bash {{ BASE_DIR }}/glance-cirros.sh

