---
# Copyright 2016 IBM Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install packages for repository
  apt: name={{ item }}
       state=present
  with_items:
    - "{{ repo_packages }}"

- name: Create folders for repository
  file: path=/srv/reprepro/ubuntu/{{ item }}
        state=directory
        owner=root
        group=root
        mode=0755
  with_items:
    - "{{ repo_folders }}"

- name: Copy config file for reprepro
  template: src={{ item }}
            dest=/srv/reprepro/ubuntu/conf/{{ item }}
            owner=root
            group=root
            mode=0644
  with_items:
    - distributions
    - options

- name: Copy site file for nginx
  template: src={{ item.src }}
            dest=/etc/nginx/{{ item.dest }}
            owner=root
            group=root
            mode=0644
  with_items:
    - { src: 'cbop-packages.conf', dest: 'sites-available/cbop-packages.conf' }
    - { src: 'server_names_hash_bucket_size.conf', dest: 'conf.d/server_names_hash_bucket_size.conf' }

- name: Create link for sites-enable
  file: src=/etc/nginx/sites-available/cbop-packages.conf
        dest=/etc/nginx/sites-enabled/cbop-packages.conf
        state=link

- name: Remove default site for nginx
  file: dest=/etc/nginx/sites-enabled/default
        state=absent

- name: Restart nginx service
  service: name=nginx
           state=restarted

