---
# Copyright 2016 IBM Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

keystone_packages:
  - ["keystone", "apache2", "libapache2-mod-wsgi"]

glance_packages:
  - ["glance"]

nova_packages:
  - ["nova-api", "nova-conductor", "nova-consoleauth", "nova-novncproxy", "nova-scheduler"]

neutron_packages:
  - ["neutron-server", "neutron-plugin-ml2", "neutron-linuxbridge-agent", "neutron-l3-agent", "neutron-dhcp-agent", "neutron-metadata-agent"]

horizon_packages:
  - ["openstack-dashboard"]

cinder_packages:
  - ["cinder-api", "cinder-scheduler"]
